- .gitignore
- hops/hdfs.py
Tested on python 2.7 and 3.6 using this [notebook](https://github.com/logicalclocks/hops-examples/blob/master/tensorflow/notebooks/Filesystem/HopsFSOperations.ipynb)
> hopsworks-631-Integrate Pydoop HDFS API into Hops API

- README.rst
- docs/hops.rst
- hops/constants.py
- hops/featurestore.py
- hops/kafka.py
- hops/tls.py
- hops/util.py
Client for:
- reading/writing from/to the feature store
- metadata operations on the feature store
- computing feature statistics
Tested with this notebook: https://github.com/Limmen/hops-examples/blob/HOPSWORKS-721/notebooks/featurestore/FeaturestoreTourPython.ipynb
> [HOPSWORKS-743]: Python client for feature store

- hops/constants.py
- hops/featurestore.py
- Add code of parsing nested spark schemas into Hive schemas
> [HOPSWORKS-928] [Featurestore] Bug: nested spark schemas not translable

- hops/featurestore.py
- Less verbose but more informative error output
> [HOPSWORKS-924] Improve error message when training dataset not found

- hops/featurestore.py
> [HOPSWORKS-911] Cache featurestore metadata on client

- hops/hdfs.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-956
> [HOPSWORKS-956] check if file/dir is already localized for hops.hdfs.copy_to_local()

- .gitignore
- Jenkinsfile
- Ship integration tests to snurran
- Don't publish artifacts and docs when building master
> [HOPSWORKS-1046] Update Jenkins pipeline

- hops/numpy_helper.py
> [HOPSWORKS-1100]

- hops/featurestore_impl/rest/rest_rpc.py
- hops/serving.py
- hops/tests/test_featurestore.py
> [HOPSWORKS-1127][hops-util-py] rest error messages parse error

- hops/featurestore_impl/featureframes/FeatureFrame.py
- missing spark argument when writing petastorm datasets
> [HOPSWORKS-1190][featurestore] bugfix

- hops/beam.py
- hops/constants.py
- hops/hdfs.py
- hops/jobs.py
- hops/serving.py
- hops/tls.py
- hops/util.py
> [HOPSWORKS-640] Beam

- hops/featurestore.py
- hops/featurestore_impl/util/fs_utils.py
- hops/tests/test_featurestore.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1321
> [Hopsworks-1321] Utility function to list feature names in feature group

- hops/tests/test_featurestore.py
- hops/tests/test_resources/featurestore_metadata.json
- setup.py
> [HPSWORKS-1021] append

- hops/featurestore.py
Fixes a docstring mistake.
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1321
> [HOPSWORKS-1321] [append] Docstring fix

- hops/featurestore.py
Fixes a missing argument in a function call
> [HOPSWORKS-1321] [append] Fix

- hops/featurestore.py
- hops/featurestore_impl/core.py
- hops/featurestore_impl/util/fs_utils.py
- Configurable in-bucket path for exporting training datasets to S3
> [HOPSWORKS-1338] [featurestore] configurable path for external tds

- hops/hdfs.py
it_tests/integration_tests.ipynb probably also need to be updated. This will be done by Robin with his refactor of the experiment system.
> [HOPSWORKS-1425] fixe code to handle path starting by hopsfs

- hops/featurestore.py
- hops/featurestore_impl/core.py
- hops/featurestore_impl/rest/rest_rpc.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1443
> [HOPSWORKS-1443][featurestore] Spark returning Infinity values for mean statistics of string type features

- hops/featurestore_impl/core.py
- hops/featurestore_impl/dao/settings/featurestore_settings.py
- hops/featurestore_impl/util/fs_utils.py
- hops/tests/test_featurestore.py
- hops/tests/test_resources/featurestore_metadata.json
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1424
> [HOPSWORKS-1424][featurestore] Handle upper/lower case for feature group names

- hops/constants.py
- hops/elasticsearch.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1476
tests: https://github.com/logicalclocks/hops-testing/pull/567
> [HOPSWORKS-1476] Add support for elasticsearch spark connector

- hops/beam.py
- hops/jobs.py
> [HOPSWORKS-1356] Jobs - parallel executions

- hops/hdfs.py
- hops/service_discovery.py
- setup.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1405
> [consul] Get webhdfs endpoint from the service discovery

- hops/experiment_impl/distribute/allreduce.py
- hops/experiment_impl/distribute/mirrored.py
- hops/experiment_impl/distribute/parameter_server.py
- hops/experiment_impl/launcher.py
- hops/experiment_impl/parallel/differential_evolution.py
- hops/experiment_impl/util/experiment_utils.py
- hops/featurestore_impl/util/fs_utils.py
- hops/tensorboard.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1821
ran the experiments tests in the integration test notebook.
> [HOPSWORKS-1821] Replace pydoop imports with hdfs module

- setup.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1877
> [HOPSWORKS-1877] Add requests as dependency to hops-util-py

- hops/featurestore.py
- hops/featurestore_impl/core.py
- hops/featurestore_impl/rest/rest_rpc.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1978
> [HOPSWORKS-1978] schematized tags

- hops/elasticsearch.py
- hops/version.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2576
> [HOPSWORKS-2576] hops-util-py - elasticsearch module - always lower case index names

- hops/experiment_impl/util/experiment_utils.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2727
> [HOPSWORKS-2727] model export issues in python kernel
